package uq.deco2800.duxcom.maps;

import java.util.Random;

import uq.deco2800.duxcom.entities.heros.AbstractHero;
import uq.deco2800.duxcom.entities.heros.BetaTester;
import uq.deco2800.duxcom.entities.heros.Ibis;
import uq.deco2800.duxcom.maps.mapgen.biomes.BiomeType;
import uq.deco2800.duxcom.maps.mapgen.generator.biomegenerator.BiomeGenerator;
import uq.deco2800.duxcom.tiles.Tile;
import uq.deco2800.duxcom.util.Array2D;

/**
 * Test map with autogenerator functionality
 * Created by liamdm on 19/08/2016.
 */
public class AutogenerateDemo extends AbstractGameMap {
    static final int MAP_WIDTH = 50;
    static final int MAP_HEIGHT = 50;

    public AutogenerateDemo() {
        super.setSize(MAP_WIDTH, MAP_HEIGHT);

        BiomeGenerator biomeGenerator = new BiomeGenerator();

        biomeGenerator.regenerateSeed();

        Array2D<Tile> tileArray2D = biomeGenerator.generateBlock(MAP_WIDTH, MAP_HEIGHT, new Random().nextBoolean() ? BiomeType.DESERT : BiomeType.TEST_REALISTIC);

        for(int y = 0; y < MAP_HEIGHT; ++y){
            for(int x = 0; x < MAP_WIDTH; ++x){
                tiles.set(x, y, tileArray2D.get(x, y));
            }
        }

        for (int i = 8; i < 9; i++) {
            for (int j = 8; j < 12; j++) {
                AbstractHero hero = new Ibis(i, j);
                addHero(hero);
            }
        }

        // Add the beta tester
        AbstractHero betaTester = new BetaTester(9, 12);
        addHero(betaTester);

        heroManager.setHero(0);
    }
}
