package uq.deco2800.duxcom.maps;

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

/**
 * Tests the Autogenerated map class
 *
 * @author Alex McLean
 */
public class AutogenerateDemoTest {

    private AutogenerateDemo autogenerateDemo;

    @Test
    public void testCreation() {
        autogenerateDemo = new AutogenerateDemo();
        assertNotNull(autogenerateDemo);
    }

}